---
project_name: go-perfguard

release:
  github:
    owner: quasilyte
    name: go-perfguard

builds:
  - binary: perfguard
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/perfguard/

archives:
  - format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
